[profile.default]
remappings = [
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/'
]
evm_version = "paris"

[etherscan]
mantle_sepolia = { chain = 5003, key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL}" }